version: "3.9"


services:
  postgres:
    image: postgres:16-alpine
    container_name: quiz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:       academia
      POSTGRES_USER:     quiz_user
      POSTGRES_PASSWORD: quiz_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz_user -d quiz_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        - "./pgadmin/pgadmin_servers.json:/pgadmin4/servers.json"
        - "./pgadmin/pgadmin_pass:/pgadmin4/pass"
      ports:
        - "5051:80"

volumes:
  postgres_data:
